name: perfect
version: 1.0.2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.14.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+5
  shared_preferences: ^2.0.12
  http: ^0.13.4
  url_launcher: ^6.0.18
  google_maps_flutter: ^2.1.2
  flutter_google_street_view: ^2.2.6
  flutter_google_places: ^0.3.0
  uuid: ^3.0.5
  geocoding: ^2.0.2
  share_plus: ^3.0.4
  youtube_player_flutter: ^8.0.0
  in_app_purchase: ^0.4.0
  html: ^0.15.0
  purchases_flutter: ^3.9.5

  #  in_app_purchase: ^2.0.1
#  purchases_flutter: ^3.9.3

  flutter: 
    sdk: flutter
  dropdown_search: ^2.0.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/image/



  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Light.otf